server:
  port: 8081
  servlet:
    context-path: /api/
  error:
    include-message: always
spring:
  application:
    name: device-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devicedb
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update